### PR TITLE
Traffic cam

### PR DESCRIPTION
**Pull request by stephensong**
first stage.

### CODE REVIEW

**Comment by henrytill** [comment]
Any particular reason you didn't want to review this before merging?

**Comment by henrytill** [comment]
I'd like to clarify that I am in favor of reviewing code changes that go into staging.  Apologies, I wasn't paying close attention when you mentioned merging this stuff.  

There are some hygienic issues here:
- you committed a lot of commented out stuff related to your backed-out `msgId` changes 
- the commits should have been squashed into a single commit before merging
- there's an empty test class

**Comment by stephensong** [comment]
I didn't mean to leave anything in about the msgId.  If I did, I will 
remove it when I find it.

I did mean to leave in some commented out stuff related to (potentially) 
moving from scalaj-http to spray-client.  I figured that once I'd got up 
to speed with spray-client (using tests as discussed) I would probably 
go back and reinstate those changes. I wasn't aware of any rules in this 
regard.

Re, the empty test case - it won't be so for very long.  I wanted to get 
these changes in before julia's stuff hit staging.  As you know, I am 
reluctant to hold off integrating changes for too long.  It is called 
"staging" after all.

Apologies as always if I have offended in any way.

(sheesh ...)

**Comment by henrytill** [comment]
Oh yep, yr right, I misspoke, the commented out stuff was indeed the `spray-client` stuff.  I don't think that WIP code should be committed as comments in staging - that's what topic branches are for.

No need to apologize, I'm not offended by any of this stuff.

I do hope we don't start treating getting changes into `staging` as a race.  I can see the possibility of that approach leading to some difficult situations down the road.

**Pull request merged**
